const TestData = {
    location: {
        name: "London",
        region: "City of London, Greater London",
        country: "United Kingdom",
        lat: 51.52,
        lon: -0.11,
        tz_id: "Europe/London",
        localtime_epoch: 1611347475,
        localtime: "2021-01-22 20:31",
    },
    current: {
        last_updated_epoch: 1611347409,
        last_updated: "2021-01-22 20:30",
        temp_c: 5.0,
        temp_f: 41.0,
        is_day: 0,
        condition: {
            text: "Partly cloudy",
            icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
            code: 1003,
        },
        wind_mph: 6.9,
        wind_kph: 11.2,
        wind_degree: 220,
        wind_dir: "SW",
        pressure_mb: 993.0,
        pressure_in: 29.8,
        precip_mm: 0.0,
        precip_in: 0.0,
        humidity: 87,
        cloud: 75,
        feelslike_c: 3.0,
        feelslike_f: 37.3,
        vis_km: 10.0,
        vis_miles: 6.0,
        uv: 1.0,
        gust_mph: 6.9,
        gust_kph: 11.2,
    },
    forecast: {
        forecastday: [
            {
                date: "2021-01-22",
                date_epoch: 1611273600,
                day: {
                    maxtemp_c: 7.5,
                    maxtemp_f: 45.5,
                    mintemp_c: 3.9,
                    mintemp_f: 39.0,
                    avgtemp_c: 5.4,
                    avgtemp_f: 41.7,
                    maxwind_mph: 8.5,
                    maxwind_kph: 13.7,
                    totalprecip_mm: 0.4,
                    totalprecip_in: 0.02,
                    avgvis_km: 10.0,
                    avgvis_miles: 6.0,
                    avghumidity: 75.0,
                    daily_will_it_rain: 1,
                    daily_chance_of_rain: "71",
                    daily_will_it_snow: 0,
                    daily_chance_of_snow: "0",
                    condition: {
                        text: "Patchy rain possible",
                        icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                        code: 1063,
                    },
                    uv: 1.0,
                },
                astro: {
                    sunrise: "07:52 AM",
                    sunset: "04:32 PM",
                    moonrise: "11:46 AM",
                    moonset: "01:59 AM",
                    moon_phase: "Waxing Gibbous",
                    moon_illumination: "62",
                },
                hour: [
                    {
                        time_epoch: 1611273600,
                        time: "2021-01-22 00:00",
                        temp_c: 5.6,
                        temp_f: 42.1,
                        is_day: 0,
                        condition: {
                            text: "Partly cloudy",
                            icon:
                                "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            code: 1003,
                        },
                        wind_mph: 8.5,
                        wind_kph: 13.7,
                        wind_degree: 283,
                        wind_dir: "WNW",
                        pressure_mb: 987.0,
                        pressure_in: 29.6,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 75,
                        cloud: 4,
                        feelslike_c: 2.7,
                        feelslike_f: 36.9,
                        windchill_c: 2.7,
                        windchill_f: 36.9,
                        heatindex_c: 5.6,
                        heatindex_f: 42.1,
                        dewpoint_c: 1.5,
                        dewpoint_f: 34.7,
                        will_it_rain: 0,
                        chance_of_rain: "0",
                        will_it_snow: 0,
                        chance_of_snow: "0",
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 9.8,
                        gust_kph: 15.8,
                        uv: 1.0,
                    },
                    {
                        time_epoch: 1611277200,
                        time: "2021-01-22 01:00",
                        temp_c: 5.4,
                        temp_f: 41.7,
                        is_day: 0,
                        condition: {
                            text: "Partly cloudy",
                            icon:
                                "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            code: 1003,
                        },
                        wind_mph: 8.3,
                        wind_kph: 13.3,
                        wind_degree: 278,
                        wind_dir: "W",
                        pressure_mb: 987.0,
                        pressure_in: 29.6,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 76,
                        cloud: 4,
                        feelslike_c: 2.5,
                        feelslike_f: 36.5,
                        windchill_c: 2.5,
                        windchill_f: 36.5,
                        heatindex_c: 5.4,
                        heatindex_f: 41.7,
                        dewpoint_c: 1.4,
                        dewpoint_f: 34.5,
                        will_it_rain: 0,
                        chance_of_rain: "0",
                        will_it_snow: 0,
                        chance_of_snow: "0",
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 9.6,
                        gust_kph: 15.5,
                        uv: 1.0,
                    },
                    {
                        time_epoch: 1611280800,
                        time: "2021-01-22 02:00",
                        temp_c: 5.1,
                        temp_f: 41.2,
                        is_day: 0,
                        condition: {
                            text: "Partly cloudy",
                            icon:
                                "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            code: 1003,
                        },
                        wind_mph: 8.3,
                        wind_kph: 13.3,
                        wind_degree: 272,
                        wind_dir: "W",
                        pressure_mb: 988.0,
                        pressure_in: 29.6,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 76,
                        cloud: 3,
                        feelslike_c: 2.2,
                        feelslike_f: 36.0,
                        windchill_c: 2.2,
                        windchill_f: 36.0,
                        heatindex_c: 5.1,
                        heatindex_f: 41.2,
                        dewpoint_c: 1.3,
                        dewpoint_f: 34.3,
                        will_it_rain: 0,
                        chance_of_rain: "0",
                        will_it_snow: 0,
                        chance_of_snow: "0",
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 9.4,
                        gust_kph: 15.1,
                        uv: 1.0,
                    },
                    {
                        time_epoch: 1611284400,
                        time: "2021-01-22 03:00",
                        temp_c: 4.9,
                        temp_f: 40.8,
                        is_day: 0,
                        condition: {
                            text: "Partly cloudy",
                            icon:
                                "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            code: 1003,
                        },
                        wind_mph: 8.1,
                        wind_kph: 13.0,
                        wind_degree: 267,
                        wind_dir: "W",
                        pressure_mb: 988.0,
                        pressure_in: 29.6,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 77,
                        cloud: 3,
                        feelslike_c: 2.0,
                        feelslike_f: 35.6,
                        windchill_c: 2.0,
                        windchill_f: 35.6,
                        heatindex_c: 4.9,
                        heatindex_f: 40.8,
                        dewpoint_c: 1.2,
                        dewpoint_f: 34.2,
                        will_it_rain: 0,
                        chance_of_rain: "0",
                        will_it_snow: 0,
                        chance_of_snow: "0",
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 9.2,
                        gust_kph: 14.8,
                        uv: 1.0,
                    },
                    {
                        time_epoch: 1611288000,
                        time: "2021-01-22 04:00",
                        temp_c: 4.8,
                        temp_f: 40.6,
                        is_day: 0,
                        condition: {
                            text: "Partly cloudy",
                            icon:
                                "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            code: 1003,
                        },
                        wind_mph: 7.6,
                        wind_kph: 12.2,
                        wind_degree: 263,
                        wind_dir: "W",
                        pressure_mb: 989.0,
                        pressure_in: 29.7,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 78,
                        cloud: 3,
                        feelslike_c: 2.0,
                        feelslike_f: 35.6,
                        windchill_c: 2.0,
                        windchill_f: 35.6,
                        heatindex_c: 4.8,
                        heatindex_f: 40.6,
                        dewpoint_c: 1.2,
                        dewpoint_f: 34.2,
                        will_it_rain: 0,
                        chance_of_rain: "0",
                        will_it_snow: 0,
                        chance_of_snow: "0",
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 8.5,
                        gust_kph: 13.7,
                        uv: 1.0,
                    },
                    {
                        time_epoch: 1611291600,
                        time: "2021-01-22 05:00",
                        temp_c: 4.6,
                        temp_f: 40.3,
                        is_day: 0,
                        condition: {
                            text: "Partly cloudy",
                            icon:
                                "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            code: 1003,
                        },
                        wind_mph: 6.9,
                        wind_kph: 11.2,
                        wind_degree: 259,
                        wind_dir: "W",
                        pressure_mb: 989.0,
                        pressure_in: 29.7,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 79,
                        cloud: 3,
                        feelslike_c: 2.0,
                        feelslike_f: 35.6,
                        windchill_c: 2.0,
                        windchill_f: 35.6,
                        heatindex_c: 4.6,
                        heatindex_f: 40.3,
                        dewpoint_c: 1.3,
                        dewpoint_f: 34.3,
                        will_it_rain: 0,
                        chance_of_rain: "0",
                        will_it_snow: 0,
                        chance_of_snow: "0",
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 8.1,
                        gust_kph: 13.0,
                        uv: 1.0,
                    },
                    {
                        time_epoch: 1611295200,
                        time: "2021-01-22 06:00",
                        temp_c: 4.5,
                        temp_f: 40.1,
                        is_day: 0,
                        condition: {
                            text: "Partly cloudy",
                            icon:
                                "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            code: 1003,
                        },
                        wind_mph: 6.5,
                        wind_kph: 10.4,
                        wind_degree: 254,
                        wind_dir: "WSW",
                        pressure_mb: 990.0,
                        pressure_in: 29.7,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 80,
                        cloud: 3,
                        feelslike_c: 2.0,
                        feelslike_f: 35.6,
                        windchill_c: 2.0,
                        windchill_f: 35.6,
                        heatindex_c: 4.5,
                        heatindex_f: 40.1,
                        dewpoint_c: 1.3,
                        dewpoint_f: 34.3,
                        will_it_rain: 0,
                        chance_of_rain: "0",
                        will_it_snow: 0,
                        chance_of_snow: "0",
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 7.4,
                        gust_kph: 11.9,
                        uv: 1.0,
                    },
                    {
                        time_epoch: 1611298800,
                        time: "2021-01-22 07:00",
                        temp_c: 4.3,
                        temp_f: 39.7,
                        is_day: 0,
                        condition: {
                            text: "Partly cloudy",
                            icon:
                                "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            code: 1003,
                        },
                        wind_mph: 6.7,
                        wind_kph: 10.8,
                        wind_degree: 255,
                        wind_dir: "WSW",
                        pressure_mb: 991.0,
                        pressure_in: 29.7,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 80,
                        cloud: 5,
                        feelslike_c: 1.7,
                        feelslike_f: 35.1,
                        windchill_c: 1.7,
                        windchill_f: 35.1,
                        heatindex_c: 4.3,
                        heatindex_f: 39.7,
                        dewpoint_c: 1.2,
                        dewpoint_f: 34.2,
                        will_it_rain: 0,
                        chance_of_rain: "0",
                        will_it_snow: 0,
                        chance_of_snow: "0",
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 8.1,
                        gust_kph: 13.0,
                        uv: 1.0,
                    },
                    {
                        time_epoch: 1611302400,
                        time: "2021-01-22 08:00",
                        temp_c: 4.1,
                        temp_f: 39.4,
                        is_day: 1,
                        condition: {
                            text: "Partly cloudy",
                            icon:
                                "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            code: 1003,
                        },
                        wind_mph: 6.9,
                        wind_kph: 11.2,
                        wind_degree: 255,
                        wind_dir: "WSW",
                        pressure_mb: 991.0,
                        pressure_in: 29.7,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 81,
                        cloud: 6,
                        feelslike_c: 1.3,
                        feelslike_f: 34.3,
                        windchill_c: 1.3,
                        windchill_f: 34.3,
                        heatindex_c: 4.1,
                        heatindex_f: 39.4,
                        dewpoint_c: 1.2,
                        dewpoint_f: 34.2,
                        will_it_rain: 0,
                        chance_of_rain: "0",
                        will_it_snow: 0,
                        chance_of_snow: "0",
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 8.5,
                        gust_kph: 13.7,
                        uv: 2.0,
                    },
                    {
                        time_epoch: 1611306000,
                        time: "2021-01-22 09:00",
                        temp_c: 3.9,
                        temp_f: 39.0,
                        is_day: 1,
                        condition: {
                            text: "Partly cloudy",
                            icon:
                                "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            code: 1003,
                        },
                        wind_mph: 7.2,
                        wind_kph: 11.5,
                        wind_degree: 255,
                        wind_dir: "WSW",
                        pressure_mb: 992.0,
                        pressure_in: 29.8,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 82,
                        cloud: 8,
                        feelslike_c: 1.0,
                        feelslike_f: 33.8,
                        windchill_c: 1.0,
                        windchill_f: 33.8,
                        heatindex_c: 3.9,
                        heatindex_f: 39.0,
                        dewpoint_c: 1.1,
                        dewpoint_f: 34.0,
                        will_it_rain: 0,
                        chance_of_rain: "0",
                        will_it_snow: 0,
                        chance_of_snow: "0",
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 9.2,
                        gust_kph: 14.8,
                        uv: 2.0,
                    },
                    {
                        time_epoch: 1611309600,
                        time: "2021-01-22 10:00",
                        temp_c: 4.7,
                        temp_f: 40.5,
                        is_day: 1,
                        condition: {
                            text: "Partly cloudy",
                            icon:
                                "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            code: 1003,
                        },
                        wind_mph: 6.9,
                        wind_kph: 11.2,
                        wind_degree: 252,
                        wind_dir: "WSW",
                        pressure_mb: 993.0,
                        pressure_in: 29.8,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 77,
                        cloud: 9,
                        feelslike_c: 2.0,
                        feelslike_f: 35.6,
                        windchill_c: 2.0,
                        windchill_f: 35.6,
                        heatindex_c: 4.7,
                        heatindex_f: 40.5,
                        dewpoint_c: 1.0,
                        dewpoint_f: 33.8,
                        will_it_rain: 0,
                        chance_of_rain: "0",
                        will_it_snow: 0,
                        chance_of_snow: "0",
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 8.7,
                        gust_kph: 14.0,
                        uv: 2.0,
                    },
                    {
                        time_epoch: 1611313200,
                        time: "2021-01-22 11:00",
                        temp_c: 5.4,
                        temp_f: 41.7,
                        is_day: 1,
                        condition: {
                            text: "Partly cloudy",
                            icon:
                                "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            code: 1003,
                        },
                        wind_mph: 6.9,
                        wind_kph: 11.2,
                        wind_degree: 248,
                        wind_dir: "WSW",
                        pressure_mb: 993.0,
                        pressure_in: 29.8,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 73,
                        cloud: 10,
                        feelslike_c: 2.9,
                        feelslike_f: 37.2,
                        windchill_c: 2.9,
                        windchill_f: 37.2,
                        heatindex_c: 5.4,
                        heatindex_f: 41.7,
                        dewpoint_c: 1.0,
                        dewpoint_f: 33.8,
                        will_it_rain: 0,
                        chance_of_rain: "0",
                        will_it_snow: 0,
                        chance_of_snow: "0",
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 8.3,
                        gust_kph: 13.3,
                        uv: 3.0,
                    },
                    {
                        time_epoch: 1611316800,
                        time: "2021-01-22 12:00",
                        temp_c: 6.2,
                        temp_f: 43.2,
                        is_day: 1,
                        condition: {
                            text: "Partly cloudy",
                            icon:
                                "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            code: 1003,
                        },
                        wind_mph: 6.7,
                        wind_kph: 10.8,
                        wind_degree: 244,
                        wind_dir: "WSW",
                        pressure_mb: 993.0,
                        pressure_in: 29.8,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 69,
                        cloud: 11,
                        feelslike_c: 3.9,
                        feelslike_f: 39.0,
                        windchill_c: 3.9,
                        windchill_f: 39.0,
                        heatindex_c: 6.2,
                        heatindex_f: 43.2,
                        dewpoint_c: 0.9,
                        dewpoint_f: 33.6,
                        will_it_rain: 0,
                        chance_of_rain: "0",
                        will_it_snow: 0,
                        chance_of_snow: "0",
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 7.8,
                        gust_kph: 12.6,
                        uv: 3.0,
                    },
                    {
                        time_epoch: 1611320400,
                        time: "2021-01-22 13:00",
                        temp_c: 6.6,
                        temp_f: 43.9,
                        is_day: 1,
                        condition: {
                            text: "Partly cloudy",
                            icon:
                                "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            code: 1003,
                        },
                        wind_mph: 6.7,
                        wind_kph: 10.8,
                        wind_degree: 239,
                        wind_dir: "WSW",
                        pressure_mb: 993.0,
                        pressure_in: 29.8,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 66,
                        cloud: 10,
                        feelslike_c: 4.5,
                        feelslike_f: 40.1,
                        windchill_c: 4.5,
                        windchill_f: 40.1,
                        heatindex_c: 6.6,
                        heatindex_f: 43.9,
                        dewpoint_c: 0.8,
                        dewpoint_f: 33.4,
                        will_it_rain: 0,
                        chance_of_rain: "0",
                        will_it_snow: 0,
                        chance_of_snow: "0",
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 7.6,
                        gust_kph: 12.2,
                        uv: 3.0,
                    },
                    {
                        time_epoch: 1611324000,
                        time: "2021-01-22 14:00",
                        temp_c: 7.1,
                        temp_f: 44.8,
                        is_day: 1,
                        condition: {
                            text: "Partly cloudy",
                            icon:
                                "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            code: 1003,
                        },
                        wind_mph: 6.5,
                        wind_kph: 10.4,
                        wind_degree: 235,
                        wind_dir: "SW",
                        pressure_mb: 993.0,
                        pressure_in: 29.8,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 64,
                        cloud: 10,
                        feelslike_c: 5.0,
                        feelslike_f: 41.0,
                        windchill_c: 5.0,
                        windchill_f: 41.0,
                        heatindex_c: 7.1,
                        heatindex_f: 44.8,
                        dewpoint_c: 0.7,
                        dewpoint_f: 33.3,
                        will_it_rain: 0,
                        chance_of_rain: "0",
                        will_it_snow: 0,
                        chance_of_snow: "0",
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 7.6,
                        gust_kph: 12.2,
                        uv: 3.0,
                    },
                    {
                        time_epoch: 1611327600,
                        time: "2021-01-22 15:00",
                        temp_c: 7.5,
                        temp_f: 45.5,
                        is_day: 1,
                        condition: {
                            text: "Partly cloudy",
                            icon:
                                "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            code: 1003,
                        },
                        wind_mph: 6.5,
                        wind_kph: 10.4,
                        wind_degree: 230,
                        wind_dir: "SW",
                        pressure_mb: 993.0,
                        pressure_in: 29.8,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 62,
                        cloud: 10,
                        feelslike_c: 5.6,
                        feelslike_f: 42.1,
                        windchill_c: 5.6,
                        windchill_f: 42.1,
                        heatindex_c: 7.5,
                        heatindex_f: 45.5,
                        dewpoint_c: 0.6,
                        dewpoint_f: 33.1,
                        will_it_rain: 0,
                        chance_of_rain: "0",
                        will_it_snow: 0,
                        chance_of_snow: "0",
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 7.4,
                        gust_kph: 11.9,
                        uv: 3.0,
                    },
                    {
                        time_epoch: 1611331200,
                        time: "2021-01-22 16:00",
                        temp_c: 6.9,
                        temp_f: 44.4,
                        is_day: 1,
                        condition: {
                            text: "Partly cloudy",
                            icon:
                                "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            code: 1003,
                        },
                        wind_mph: 6.0,
                        wind_kph: 9.7,
                        wind_degree: 216,
                        wind_dir: "SW",
                        pressure_mb: 993.0,
                        pressure_in: 29.8,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 67,
                        cloud: 23,
                        feelslike_c: 5.1,
                        feelslike_f: 41.2,
                        windchill_c: 5.1,
                        windchill_f: 41.2,
                        heatindex_c: 6.9,
                        heatindex_f: 44.4,
                        dewpoint_c: 1.2,
                        dewpoint_f: 34.2,
                        will_it_rain: 0,
                        chance_of_rain: "0",
                        will_it_snow: 0,
                        chance_of_snow: "0",
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 7.2,
                        gust_kph: 11.5,
                        uv: 3.0,
                    },
                    {
                        time_epoch: 1611334800,
                        time: "2021-01-22 17:00",
                        temp_c: 6.4,
                        temp_f: 43.5,
                        is_day: 0,
                        condition: {
                            text: "Partly cloudy",
                            icon:
                                "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            code: 1003,
                        },
                        wind_mph: 5.4,
                        wind_kph: 8.6,
                        wind_degree: 203,
                        wind_dir: "SSW",
                        pressure_mb: 993.0,
                        pressure_in: 29.8,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 73,
                        cloud: 36,
                        feelslike_c: 4.6,
                        feelslike_f: 40.3,
                        windchill_c: 4.6,
                        windchill_f: 40.3,
                        heatindex_c: 6.4,
                        heatindex_f: 43.5,
                        dewpoint_c: 1.8,
                        dewpoint_f: 35.2,
                        will_it_rain: 0,
                        chance_of_rain: "0",
                        will_it_snow: 0,
                        chance_of_snow: "0",
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 6.9,
                        gust_kph: 11.2,
                        uv: 1.0,
                    },
                    {
                        time_epoch: 1611338400,
                        time: "2021-01-22 18:00",
                        temp_c: 5.8,
                        temp_f: 42.4,
                        is_day: 0,
                        condition: {
                            text: "Partly cloudy",
                            icon:
                                "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            code: 1003,
                        },
                        wind_mph: 4.9,
                        wind_kph: 7.9,
                        wind_degree: 190,
                        wind_dir: "S",
                        pressure_mb: 993.0,
                        pressure_in: 29.8,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 79,
                        cloud: 48,
                        feelslike_c: 4.1,
                        feelslike_f: 39.4,
                        windchill_c: 4.1,
                        windchill_f: 39.4,
                        heatindex_c: 5.8,
                        heatindex_f: 42.4,
                        dewpoint_c: 2.4,
                        dewpoint_f: 36.3,
                        will_it_rain: 0,
                        chance_of_rain: "0",
                        will_it_snow: 0,
                        chance_of_snow: "0",
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 6.7,
                        gust_kph: 10.8,
                        uv: 1.0,
                    },
                    {
                        time_epoch: 1611342000,
                        time: "2021-01-22 19:00",
                        temp_c: 5.5,
                        temp_f: 41.9,
                        is_day: 0,
                        condition: {
                            text: "Light rain shower",
                            icon:
                                "//cdn.weatherapi.com/weather/64x64/night/353.png",
                            code: 1240,
                        },
                        wind_mph: 5.1,
                        wind_kph: 8.3,
                        wind_degree: 200,
                        wind_dir: "SSW",
                        pressure_mb: 993.0,
                        pressure_in: 29.8,
                        precip_mm: 0.1,
                        precip_in: 0.0,
                        humidity: 80,
                        cloud: 66,
                        feelslike_c: 3.6,
                        feelslike_f: 38.5,
                        windchill_c: 3.6,
                        windchill_f: 38.5,
                        heatindex_c: 5.5,
                        heatindex_f: 41.9,
                        dewpoint_c: 2.3,
                        dewpoint_f: 36.1,
                        will_it_rain: 0,
                        chance_of_rain: "24",
                        will_it_snow: 0,
                        chance_of_snow: "0",
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 7.2,
                        gust_kph: 11.5,
                        uv: 1.0,
                    },
                    {
                        time_epoch: 1611345600,
                        time: "2021-01-22 20:00",
                        temp_c: 5.1,
                        temp_f: 41.2,
                        is_day: 0,
                        condition: {
                            text: "Partly cloudy",
                            icon:
                                "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            code: 1003,
                        },
                        wind_mph: 5.6,
                        wind_kph: 9.0,
                        wind_degree: 211,
                        wind_dir: "SSW",
                        pressure_mb: 993.0,
                        pressure_in: 29.8,
                        precip_mm: 0.3,
                        precip_in: 0.01,
                        humidity: 81,
                        cloud: 83,
                        feelslike_c: 3.1,
                        feelslike_f: 37.6,
                        windchill_c: 3.1,
                        windchill_f: 37.6,
                        heatindex_c: 5.1,
                        heatindex_f: 41.2,
                        dewpoint_c: 2.2,
                        dewpoint_f: 36.0,
                        will_it_rain: 0,
                        chance_of_rain: "47",
                        will_it_snow: 0,
                        chance_of_snow: "0",
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 7.8,
                        gust_kph: 12.6,
                        uv: 1.0,
                    },
                    {
                        time_epoch: 1611349200,
                        time: "2021-01-22 21:00",
                        temp_c: 4.8,
                        temp_f: 40.6,
                        is_day: 0,
                        condition: {
                            text: "Light rain shower",
                            icon:
                                "//cdn.weatherapi.com/weather/64x64/night/353.png",
                            code: 1240,
                        },
                        wind_mph: 5.8,
                        wind_kph: 9.4,
                        wind_degree: 222,
                        wind_dir: "SW",
                        pressure_mb: 993.0,
                        pressure_in: 29.8,
                        precip_mm: 0.4,
                        precip_in: 0.02,
                        humidity: 83,
                        cloud: 100,
                        feelslike_c: 2.6,
                        feelslike_f: 36.7,
                        windchill_c: 2.6,
                        windchill_f: 36.7,
                        heatindex_c: 4.8,
                        heatindex_f: 40.6,
                        dewpoint_c: 2.1,
                        dewpoint_f: 35.8,
                        will_it_rain: 1,
                        chance_of_rain: "71",
                        will_it_snow: 0,
                        chance_of_snow: "0",
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 8.3,
                        gust_kph: 13.3,
                        uv: 1.0,
                    },
                    {
                        time_epoch: 1611352800,
                        time: "2021-01-22 22:00",
                        temp_c: 4.5,
                        temp_f: 40.1,
                        is_day: 0,
                        condition: {
                            text: "Overcast",
                            icon:
                                "//cdn.weatherapi.com/weather/64x64/night/122.png",
                            code: 1009,
                        },
                        wind_mph: 5.6,
                        wind_kph: 9.0,
                        wind_degree: 228,
                        wind_dir: "SW",
                        pressure_mb: 993.0,
                        pressure_in: 29.8,
                        precip_mm: 0.3,
                        precip_in: 0.01,
                        humidity: 83,
                        cloud: 100,
                        feelslike_c: 2.3,
                        feelslike_f: 36.1,
                        windchill_c: 2.3,
                        windchill_f: 36.1,
                        heatindex_c: 4.5,
                        heatindex_f: 40.1,
                        dewpoint_c: 1.9,
                        dewpoint_f: 35.4,
                        will_it_rain: 0,
                        chance_of_rain: "47",
                        will_it_snow: 0,
                        chance_of_snow: "0",
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 8.1,
                        gust_kph: 13.0,
                        uv: 1.0,
                    },
                    {
                        time_epoch: 1611356400,
                        time: "2021-01-22 23:00",
                        temp_c: 4.3,
                        temp_f: 39.7,
                        is_day: 0,
                        condition: {
                            text: "Light rain shower",
                            icon:
                                "//cdn.weatherapi.com/weather/64x64/night/353.png",
                            code: 1240,
                        },
                        wind_mph: 5.6,
                        wind_kph: 9.0,
                        wind_degree: 235,
                        wind_dir: "SW",
                        pressure_mb: 993.0,
                        pressure_in: 29.8,
                        precip_mm: 0.1,
                        precip_in: 0.0,
                        humidity: 83,
                        cloud: 100,
                        feelslike_c: 2.1,
                        feelslike_f: 35.8,
                        windchill_c: 2.1,
                        windchill_f: 35.8,
                        heatindex_c: 4.3,
                        heatindex_f: 39.7,
                        dewpoint_c: 1.6,
                        dewpoint_f: 34.9,
                        will_it_rain: 0,
                        chance_of_rain: "24",
                        will_it_snow: 0,
                        chance_of_snow: "0",
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 8.1,
                        gust_kph: 13.0,
                        uv: 1.0,
                    },
                ],
            },
        ],
    },
};

export default TestData;
